import Head from "next/head";
import styles from "../styles/Home.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
// import { faYoutube } from "@fortawesome/free-brands-svg-icons";

// import the library
import { library } from "@fortawesome/fontawesome-svg-core";

import { faCode, faHighlighter } from "@fortawesome/free-solid-svg-icons";
import {
  faGithubAlt,
  faGoogle,
  faFacebook,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="twitter:card" content="summary" key="twcard" />
        <meta name="twitter:title" content="Testing" />
        <meta
          name="twitter:description"
          content="TestingTestingTestingTestingTestingTestingTestingTestingTestingTestingTesting"
        />
        <meta
          name="twitter:image:src"
          content="https://images.unsplash.com/photo-1574169208507-84376144848b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8aW1hZ2V8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"
        />
      </Head>

      <main className={styles.main}>
        <p>
          Hello <FontAwesomeIcon height={10} width={10} icon={faTwitter} />{" "}
          World!
        </p>
      </main>
    </div>
  );
}
